afk-filmkreis.de/public_html/protected/models/Guestbook.php
<?php

/**
 * This is the model class for table "{{guestbook}}".
 *
 * The followings are the available columns in table '{{guestbook}}':
 * @property integer $id
 * @property string $titel
 * @property string $name
 * @property string $mail
 * @property string $text
 * @property string $iphash
 * @property string $timestamp
 */
class Guestbook extends CActiveRecord
{
	
	public $validacion;
	/**
	 * Returns the static model of the specified AR class.
	 * @return Guestbook the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return '{{guestbook}}';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('titel, text, iphash', 'required'),
			array('titel, name, mail', 'length', 'max'=>255),
			array('iphash', 'length', 'max'=>32),
			// The following rule is used by search().
			// Please remove those attributes that should not be searched.
			array('id, titel, name, mail, text, iphash, timestamp', 'safe', 'on'=>'search'),
			array(
                     'validacion',
                     'application.extensions.recaptcha.EReCaptchaValidator',
                     'privateKey'=> Yii::app()->params['reCaptcha']['privateKey'], 
                     'on' => 'entrywcaptcha'
                 ),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'ID',
			'titel' => 'Titel',
			'name' => 'Name',
			'mail' => 'E-Mail-Adresse',
			'text' => 'Text',
			'iphash' => 'Iphash',
			'timestamp' => 'Timestamp',
			'validacion'=>Yii::t('demo', 'Enter both words separated by a space: '),
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 * @return CActiveDataProvider the data provider that can return the models based on the search/filter conditions.
	 */
	public function search()
	{
		// Warning: Please modify the following code to remove attributes that
		// should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('id',$this->id);
		$criteria->compare('titel',$this->titel,true);
		$criteria->compare('name',$this->name,true);
		$criteria->compare('mail',$this->mail,true);
		$criteria->compare('text',$this->text,true);
		$criteria->compare('iphash',$this->iphash,true);
		$criteria->compare('timestamp',$this->timestamp,true);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}
}

afk-filmkreis.de/public_html/protected/controllers/GuestbookController.php
<?php

class GuestbookController extends Controller {
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout = '//layouts/column2';

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id) {
		$this -> render('view', array('model' => $this -> loadModel($id), ));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate() {
		$model = new Guestbook;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);
		$model -> scenario = 'entrywcaptcha';

		if (isset($_POST['Guestbook']) && empty($_POST['mail'])) {
			$model -> attributes = $_POST['Guestbook'];
			$model -> iphash = md5(Yii::app() -> request -> userHostAddress);

			if (strpos($_POST['Guestbook']['Text'], "href") !== false) {
				$model -> public = 0;
			} else {
				$model -> public = 1;
			}

			if ($model -> validate()) {
				$model -> scenario = NULL;
				Yii::log("Neuer Gästebucheintrag", 'guestbook', 'guestbook');
				if ($model -> save(false))
					$this -> redirect(array('index'));
			}

		}

		$this -> render('create', array('model' => $model, ));
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex() {
		$dataProvider = new CActiveDataProvider('Guestbook', array('criteria' => array('condition'=>'public=1','order' => 'timestamp DESC', ), ));
		$this -> render('index', array('dataProvider' => $dataProvider, ));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer the ID of the model to be loaded
	 */
	public function loadModel($id) {
		$model = Guestbook::model() -> findByPk($id);
		if ($model === null)
			throw new CHttpException(404, 'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param CModel the model to be validated
	 */
	protected function performAjaxValidation($model) {
		if (isset($_POST['ajax']) && $_POST['ajax'] === 'guestbook-form') {
			echo CActiveForm::validate($model);
			Yii::app() -> end();
		}
	}

}

afk-filmkreis.de/public_html/protected/views/guestbook/_form.php
<div class="form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'guestbook-form',
	'enableAjaxValidation'=>false,
)); ?>


	<?php echo $form->errorSummary($model); ?>

	<div class="row">
		<?php echo $form->labelEx($model,'titel'); ?>
		<?php echo $form->textField($model,'titel',array('size'=>60,'maxlength'=>255)); ?>
		<?php echo $form->error($model,'titel'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'name'); ?>
		<?php echo $form->textField($model,'name',array('size'=>60,'maxlength'=>255)); ?>
		<?php echo $form->error($model,'name'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'mail'); ?>
		<?php echo $form->textField($model,'mail',array('size'=>60,'maxlength'=>255)); ?>
		<?php echo $form->error($model,'mail'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'text'); ?>
		<?php echo $form->textArea($model,'text',array('rows'=>10, 'cols'=>50)); ?>
		<?php echo $form->error($model,'text'); ?>
	</div>
	<div class="bagrfihi">
		<?php echo $form->labelEx($model,'text'); ?>
		<?php echo CHtml::textField('mail') ?>
		<?php echo $form->error($model,'text'); ?>
	</div>
	<?php echo CHtml::activeLabel($model, 'validacion'); ?>
	<?php $this->widget('application.extensions.recaptcha.EReCaptcha', 
	   array('model'=>$model, 'attribute'=>'validacion',
	         'theme'=>'white', 'language'=>'de', 
	         'publicKey'=>Yii::app()->params['reCaptcha']['publicKey'] )) ?>
	<?php echo CHtml::error($model, 'validacion'); ?>

	<div class="row buttons">
		<?php echo CHtml::submitButton($model->isNewRecord ? 'Create' : 'Save'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- form -->

afk-filmkreis.de/public_html/protected/views/guestbook/_view.php
<div class="post">
	<div class="title">
		<?php echo CHtml::encode($data->titel); ?>
	</div>
	<div class="author">
		geschrieben von <?php echo CHtml::encode($data->name); ?> am <?php echo CHtml::encode($data->timestamp); ?>
	</div>
	<div class="content">
		<?php
			$this->beginWidget('CMarkdown', array('purifyOutput'=>true));
			echo CHtml::encode($data->text);
			$this->endWidget();
		?>
	</div>
	<div class="nav">
	<?php //echo ($data->update_time != 0) ?  ("Letztes Update am ". date('d.m.Y',$data->update_time)) : ""; ?>
		
	</div>
</div>


<?php 
	/*

<div class="gbcontainer">
	<div class="gbcontainerheader"><?php echo CHtml::encode($data->titel); ?></div>
	<div>
	dfgihdfspog hpsdf gudhfspguds gdsupgfdshgifu doifdu hfdus hg dush
	</div>

</div>

<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('name')); ?>:</b>
	<?php echo CHtml::encode($data->name); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('text')); ?>:</b>
	<?php echo CHtml::encode($data->text); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('timestamp')); ?>:</b>
	<?php echo CHtml::encode($data->timestamp); ?>
	<br />*/
?>

afk-filmkreis.de/public_html/protected/views/guestbook/create.php
<?php
$this->breadcrumbs=array(
	'Guestbooks'=>array('index'),
	'Create',
);

$this->menu=array(
	array('label'=>'List Guestbook', 'url'=>array('index')),
	array('label'=>'Manage Guestbook', 'url'=>array('admin')),
);
?>

<h1>Ins Gästebuch eintragen</h1>

<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>

<?php echo CHtml::Link('Zurück zum Gästebuch', array('guestbook/index')); ?>

afk-filmkreis.de/public_html/protected/views/guestbook/index.php
<?php
$this->breadcrumbs=array(
	'Guestbooks',
);

$this->menu=array(
	array('label'=>'Create Guestbook', 'url'=>array('create')),
	array('label'=>'Manage Guestbook', 'url'=>array('admin')),
);
?>

<h1>Gästebuch</h1>

<?php echo CHtml::Link('Ins Gästebuch eintragen', array('guestbook/create')); ?>

<?php $this->widget('zii.widgets.CListView', array(
	'dataProvider'=>$dataProvider,
	'itemView'=>'_view',
	'summaryText'=>'Ergebnisse {start} - {end} von insgesamt {count} Einträgen.',
)); ?>